name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v7

      - name: Install deps
        run: npm i --locked

      - name: Typescript Build
        # Honestly how hard is it to use an exit code come on now
        run: |
          npx nuxt typecheck | tee err
          exit $(grep error -c err)
